javafx:
  title: ${spring.application.name}
  stage:
    resizable: true

spring:
  application:
    name: agendaFx
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging:
  file: logs/${spring.application.name}.log
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE