info:
  author: greboreda
  app-name: agendaFx

javafx:
  title: ${info.app-name}
  stage:
    resizable: true

spring:
  application:
    name: ${info.app-name}
  main:
    banner-mode: console
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging:
  file: logs/${info.app-name}.log
  level:
    root: WARN
    greboreda.agendafx: INFO
    org.hibernate.SQL: DEBUG