DROP TABLE IF EXISTS PERSONPHONE;
DROP TABLE IF EXISTS PERSON;
DROP TABLE IF EXISTS PHONE;
DROP SEQUENCE IF EXISTS PERSON_SEQ;
DROP SEQUENCE IF EXISTS PHONE_SEQ;

CREATE SEQUENCE PERSON_SEQ
	START WITH 1
	INCREMENT BY 1;

CREATE TABLE PERSON (
	ID INTEGER DEFAULT PERSON_SEQ.NEXTVAL PRIMARY KEY,
	FIRSTNAME VARCHAR(256) NOT NULL,
	LASTNAME VARCHAR(256) NOT NULL,
	CONSTRAINT UNIQUE_COMPLETE_NAME UNIQUE (FIRSTNAME, LASTNAME)
);

CREATE SEQUENCE PHONE_SEQ
	START WITH 1
	INCREMENT BY 1;

CREATE TABLE PHONE (
	ID INTEGER DEFAULT PHONE_SEQ.NEXTVAL PRIMARY KEY,
	NUMBER VARCHAR(20),
	PREFIX VARCHAR(10),
	CONSTRAINT UNIQUE_COMPLETE_PHONE UNIQUE (`NUMBER`, PREFIX)
);

CREATE TABLE PERSONPHONE (
	PERSONID INTEGER NOT NULL,
	PHONEID INTEGER NOT NULL,
	PRIMARY KEY (PERSONID, PHONEID),
	CONSTRAINT FK_PERSON FOREIGN KEY (PERSONID) REFERENCES PERSON(ID),
	CONSTRAINT FX_PHONE FOREIGN KEY (PHONEID) REFERENCES PHONE(ID)
);
