DELETE FROM PERSONPHONE;
DELETE FROM PERSON;
DELETE FROM PHONE;

ALTER SEQUENCE PHONE_SEQ RESTART WITH 1;
ALTER SEQUENCE PERSON_SEQ RESTART WITH 1;

INSERT INTO PERSON (FIRSTNAME, LASTNAME) VALUES ('John', 'Doe');
INSERT INTO PERSON (FIRSTNAME, LASTNAME) VALUES ('Michael', 'Jackson');

INSERT INTO PERSON(FIRSTNAME, LASTNAME) VALUES ('Aaron', 'Aaronson');
INSERT INTO PERSON(FIRSTNAME, LASTNAME) VALUES ('Zack', 'Zackary');

INSERT INTO PHONE(`NUMBER`, PREFIX) VALUES ('666666666', 34);
INSERT INTO PHONE(`NUMBER`, PREFIX) VALUES ('696969696', 34);

INSERT INTO PERSONPHONE(PERSONID, PHONEID)
SELECT PE.ID, PO.ID
FROM PERSON PE, PHONE PO
WHERE PE.FIRSTNAME = 'John' AND PE.LASTNAME = 'Doe'
AND PO.PREFIX = '34' AND PO.NUMBER = '666666666';

INSERT INTO PERSONPHONE(PERSONID, PHONEID)
SELECT PE.ID, PO.ID
FROM PERSON PE, PHONE PO
WHERE PE.FIRSTNAME = 'Michael' AND PE.LASTNAME = 'Jackson'
AND PO.PREFIX = '34' AND PO.NUMBER = '696969696';

COMMIT;